In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [3]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

# 1

In [4]:
type(list_)

list

In [5]:
type(array_list)

numpy.ndarray

# 2

In [10]:

# Print the data type of each element in the numpy array
print("Data type of elements in array_list:")
for element in array_list:
    print(type(element))

# Print the data type of each element in the list
print("Data type of elements in list_:")
for element in list_:
    print(type(element))

Data type of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


# 3

In [15]:
array_list = np.array(object = list_, dtype = int)

In [16]:
array_list

array([1, 2, 3, 4, 5])

In [17]:
# Print the data type of each element in the numpy array
print("Data type of elements in array_list:")
for element in array_list:
    print(type(element))

# Print the data type of each element in the list
print("Data type of elements in list_:")
for element in list_:
    print(type(element))

Data type of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [ ]:
# Consider the below code to answer further questions:

In [18]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [19]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

# 4

In [20]:
num_array.size

6

In [21]:
num_array.shape

(2, 3)

# 5

In [22]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# 6

In [24]:
np.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])